name: Deploy to Render

# Trigger the action on push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub (if needed)
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the Docker image to Render
    - name: Build and push Docker image to Render
      uses: render-examples/ci-docker-deploy@v1
      with:
        email: ${{ secrets.HEROKU_EMAIL }} # Render doesn't need this, use any email
        api_key: ${{ secrets.RENDER_API_KEY }}  # Set your Render API Key in GitHub Secrets
        app_name: ${{ secrets.RENDER_APP_NAME }}  # Set your Render app name in GitHub Secrets
        dockerfile_directory: ./  # Your Dockerfile location
        dockerfile_name: Dockerfile  # Your Dockerfile name
        process_type: web
